Feature/ble
juztins-lab/roast-meter pull request #7
Opened 2023-05-09 19:55 UTC by chawasit

# Description
I have tried to implement some BLE functionality and a basic web app using web Bluetooth API. Right now, it can only connect and show real-time Agtron value.
Here is a [WebApp](https://roast-meter-app.hh.coffee/) you can test and [WebApp Repo](https://github.com/chawasit/roast-meter-app)

## Todos
- [x] Add Platform IO Project - I am just comfortable working with PlatformIO (better compile-time and IDE). The code is still compiled with ArduinoIDE (Tested on v2.1.0)
- [x] EEPROM - Store setting in EEPROM so that it can be changed from BLE App in the future.
- BLE 
    - RoastMeter Service
        - [x] Agtron Level - read and notify
        - [x] Particle Reading - read and notify
    - Setting Service
        - [ ] LED Brightness - change sensor LED Brightness (read and write)
        - [ ] Intersection Point - change Agtron Intersection Point (read and write)
        - [ ] Deviation - change Agtron Deviation  (read and write)
        - [ ] BLE Name - set advertise name (read and write)

## Test 
- Flash Firmware
- Browse https://roast-meter-app.hh.coffee/ 
- Click on the text
- Allow permission on the first try
- Select "Roast Meter XX:XX" on the list to connect

2023-05-12 12:44 UTC, juztins-lab commented
hey, THANK YOU! for your contribution, I have tested your work and it seems to be working!
I will integrate your work with the changes we have in the beta version and add it as a separate version of the Roast meter.
The idea behind the BT function will be to be able to calibrate remotely but also do readings and maybe customize the reading scale.

2023-05-12 14:14 UTC, yakste commented
I'm confused, I did some late night viewing of GitHub but haven't
contributed to code. I apologize for anything I may have done that
triggered this email, I was only wondering how to try the BT code.

On Fri, May 12, 2023, 5:44 AM Juztin ***@***.***> wrote:

> hey, THANK YOU! for your contribution, I have tested your work and it
> seems to be working!
> I will integrate your work with the changes we have in the beta version
> and add it as a separate version of the Roast meter.
> The idea behind the BT function will be to be able to calibrate remotely
> but also do readings and maybe customize the reading scale.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juztins-lab/roast-meter/pull/7#issuecomment-1545688137>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7KTJQQE6STHC5GDOVEXMDLXFYWDVANCNFSM6AAAAAAX3YM6MI>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-05-12 17:59 UTC, chawasit commented
I am happy to hear that. 😄 

I have implemented the handler functions to save the new setting from BT to EEPROM. But I didn't test it on the actual unit yet. (I left my roast meter at my coffee trainer workshop. They will have a roasting class next week and are happy to try the roast meter. I also ask them to log the result for further calibration.)

So, the roast meter should be able to change LED Brightness and the Agtron formula Intersection Poin and Deviation in real-time.

I plan to implement this part of the web app in the next week.

Also, You can test the raw BT functions by using this app. [nRF Connect Android](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en&gl=US) or [nRF Connect iOS](https://apps.apple.com/th/app/nrf-connect-for-mobile/id1054362403?l=th)

2023-05-14 07:56 UTC, chawasit commented
I have reimplemented the web app using vue3.
Right now it has Setting page that able to change LED Brightness and the Agtron formula Intersection Point and Deviation remotely.

2023-05-14 17:43 UTC, juztins-lab commented
Thanks for the update! I will take a look as soon as I can. 
Another thing I failed to mention is that we started using heavily the beta version with increased resolution, the implementation you can see here (https://github.com/juztins-lab/roast-meter/blob/increased-resolution/src/roast_meter.ino).
You can integrate the changes, if not I will do it after you have a "complete" version of the implementation.

2023-05-15 18:23 UTC, chawasit commented
Oh, I did not see that branch yet.

What are the settings you want to remotely config? I will add them to BT to make it easier to test some settings without reflashing the firmware.

2023-05-15 19:47 UTC, juztins-lab commented on src/main.cpp
Can you please rename the file to roast_meter_ble.cpp ? We will want to integrate both versions in the how to guides.

2023-05-15 19:47 UTC, juztins-lab commented on src/roast_meter.ino
Re-add please the version from the enhanced-precision as roast_meter.ino

2023-05-15 19:48 UTC, juztins-lab requested changes
Hi, please see the comments for the pull-request.
Thank you again for the awesome work!

2023-05-15 19:51 UTC, juztins-lab commented on src/main.cpp
Also, can you please explain what is the point of the warm up timer? Might be good to also  save a last used date so that repetitive on/off don't have to wait 60sec.

2023-05-15 20:06 UTC, juztins-lab approved these changes

2023-05-15 20:06 UTC, merged

2023-05-15 20:22 UTC, chawasit commented on src/main.cpp
I might be misunderstood. The IR LED changes its frequency slightly depending on the temperature. So it is good to give it some time for the internal temperature to stabilize before first reading.

2023-05-15 20:47 UTC, chawasit commented on src/main.cpp
I test it with low power and max power setting. In my case, the temperature change is about 0.5 c from power-up . So, it should be safe to remove the warm-up phase. When I add the warm-up, I assume it will go up more than that.